import { requirementService, candidateService, userService, interviewService, offerService, feedbackService, searchService, portalService, skillService, departmentService, clientService, interviewPanelService } from './http'
import { vendorService } from './http/vendors'
import { vendorPortalService } from './http/vendorPortal'
import { referralPortalService } from './http/referralPortal'
import { activityLogService } from './http/activityLogs'

export const api = {
    requirements: {
        list: requirementService.getAll,
        getPending: requirementService.getPending,
        getById: requirementService.getById,
        create: requirementService.create,
        update: requirementService.update,
        updateStatus: requirementService.updateStatus,
        updateHiringStage: requirementService.updateHiringStage,
        cancel: requirementService.cancel,
        assignRecruiter: requirementService.assignRecruiter,
        unassignRecruiter: requirementService.unassignRecruiter,
        approve: requirementService.approve,
        reject: requirementService.reject,
        setVisibility: requirementService.setVisibility,
        setReferralVisibility: requirementService.setReferralVisibility,
        delete: requirementService.delete,
        getMatchingProfiles: requirementService.getMatchingProfiles,
        linkCandidate: requirementService.linkCandidate,
        getInterviewPlan: requirementService.getInterviewPlan,
        updateInterviewPlan: requirementService.updateInterviewPlan,
        getCandidateInterviewProgress: requirementService.getCandidateInterviewProgress,
    },
    candidates: {
        list: candidateService.getAll,
        checkEmail: candidateService.checkEmail,
        parseResume: candidateService.parseResume,
        getByRequirementId: candidateService.getByRequirementId,
        get: candidateService.getById,
        create: candidateService.create,
        update: candidateService.update,
        updateStatus: candidateService.updateStatus,
        uploadResume: candidateService.uploadResume,
        fetchResume: candidateService.fetchResume,
        deleteResume: candidateService.deleteResume,
        delete: candidateService.delete,
    },
    activityLogs: {
        log: activityLogService.logActivity,
        getByEntity: activityLogService.getByEntity,
        list: activityLogService.getAll
    },
    search: {
        query: searchService.query,
    },
    portal: {
        getMe: portalService.getMe,
        getApplications: portalService.getApplications,
        getApplication: portalService.getApplication,
        saveProfile: portalService.saveProfile,
        uploadResume: portalService.uploadResume,
        getOpenPositions: portalService.getOpenPositions,
        getPosition: portalService.getPosition,
        applyToPosition: portalService.applyToPosition,
    },
    vendors: {
        list: vendorService.list,
        get: vendorService.get,
        create: vendorService.create,
        update: vendorService.update,
        assignJobs: vendorService.assignJobs,
        unassignJob: vendorService.unassignJob,
        inviteUser: vendorService.inviteUser,
    },
    vendorPortal: {
        getMe: vendorPortalService.getMe,
        getPositions: vendorPortalService.getPositions,
        getPosition: vendorPortalService.getPosition,
        getSubmissions: vendorPortalService.getSubmissions,
        parseResume: vendorPortalService.parseResume,
        checkEmail: vendorPortalService.checkEmail,
        submitCandidate: vendorPortalService.submitCandidate,
        uploadResume: vendorPortalService.uploadResume,
    },
    referralPortal: {
        getMe: referralPortalService.getMe,
        getPositions: referralPortalService.getPositions,
        getDepartments: referralPortalService.getDepartments,
        getPosition: referralPortalService.getPosition,
        getReferrals: referralPortalService.getReferrals,
        getReferral: referralPortalService.getReferral,
        parseResume: referralPortalService.parseResume,
        checkEmail: referralPortalService.checkEmail,
        submitReferral: referralPortalService.submitReferral,
        uploadResume: referralPortalService.uploadResume,
    },
    skills: {
        list: skillService.list,
        create: skillService.create,
        remove: skillService.remove,
    },
    departments: {
        list: departmentService.list,
        create: departmentService.create,
        remove: departmentService.remove,
    },
    clients: {
        list: clientService.list,
        create: clientService.create,
        remove: clientService.remove,
    },
    interviewPanels: {
        list: interviewPanelService.list,
        seed: interviewPanelService.seed,
        update: interviewPanelService.update,
    },
    users: {
        list: userService.list,
        get: userService.getById,
        updateMe: userService.updateMe,
        update: userService.update,
        updateProfile: userService.updateProfile,
        resetPassword: userService.resetPassword,
        updateRole: userService.updateRole,
        toggleStatus: userService.toggleStatus,
        invite: userService.invite,
        getLoginHistory: userService.getLoginHistory,
        updateTags: userService.updateTags,
    },
    interviews: {
        list: interviewService.getAll,
        get: interviewService.getById,
        getByCandidateId: interviewService.getByCandidateId,
        create: interviewService.create,
        update: interviewService.update,
        updateStatus: interviewService.updateStatus,
        fetchCandidateResume: interviewService.fetchCandidateResume,
        numberOfInterviews: async () => (await interviewService.getAll()).length
    },
    feedback: {
        getByInterviewId: feedbackService.getByInterviewId,
        getByCandidateId: feedbackService.getByCandidateId,
        get: feedbackService.getById,
        create: feedbackService.create,
        remove: feedbackService.remove,
        downloadHtml: feedbackService.downloadHtml,
    },
    offers: {
        list: offerService.getAll,
        get: offerService.getById,
        getByCandidateId: offerService.getByCandidateId,
        create: offerService.create,
        update: offerService.update,
        updateStatus: offerService.updateStatus
    },
}
