/** Default IT skills seeded into SkillCatalog on first load. */
export const DEFAULT_SKILL_CATALOG: { name: string; category: string }[] = [
  { name: 'JavaScript', category: 'Languages' },
  { name: 'TypeScript', category: 'Languages' },
  { name: 'Python', category: 'Languages' },
  { name: 'Java', category: 'Languages' },
  { name: 'C#', category: 'Languages' },
  { name: 'C++', category: 'Languages' },
  { name: 'Go', category: 'Languages' },
  { name: 'Rust', category: 'Languages' },
  { name: 'Kotlin', category: 'Languages' },
  { name: 'Swift', category: 'Languages' },
  { name: 'PHP', category: 'Languages' },
  { name: 'Ruby', category: 'Languages' },
  { name: 'Scala', category: 'Languages' },
  { name: 'R', category: 'Languages' },
  { name: 'SQL', category: 'Data' },
  { name: 'PL/SQL', category: 'Data' },
  { name: 'React', category: 'Frontend' },
  { name: 'Next.js', category: 'Frontend' },
  { name: 'Angular', category: 'Frontend' },
  { name: 'Vue.js', category: 'Frontend' },
  { name: 'HTML', category: 'Frontend' },
  { name: 'CSS', category: 'Frontend' },
  { name: 'Tailwind CSS', category: 'Frontend' },
  { name: 'SASS', category: 'Frontend' },
  { name: 'Redux', category: 'Frontend' },
  { name: 'Webpack', category: 'Frontend' },
  { name: 'Vite', category: 'Frontend' },
  { name: 'Node.js', category: 'Backend' },
  { name: 'Express', category: 'Backend' },
  { name: 'NestJS', category: 'Backend' },
  { name: 'Django', category: 'Backend' },
  { name: 'Flask', category: 'Backend' },
  { name: 'FastAPI', category: 'Backend' },
  { name: 'Spring Boot', category: 'Backend' },
  { name: '.NET', category: 'Backend' },
  { name: 'GraphQL', category: 'Backend' },
  { name: 'REST APIs', category: 'Backend' },
  { name: 'Microservices', category: 'Backend' },
  { name: 'PostgreSQL', category: 'Data' },
  { name: 'MySQL', category: 'Data' },
  { name: 'MongoDB', category: 'Data' },
  { name: 'Redis', category: 'Data' },
  { name: 'Elasticsearch', category: 'Data' },
  { name: 'DynamoDB', category: 'Data' },
  { name: 'Snowflake', category: 'Data' },
  { name: 'dbt', category: 'Data' },
  { name: 'Apache Spark', category: 'Data' },
  { name: 'Hadoop', category: 'Data' },
  { name: 'Kafka', category: 'Data' },
  { name: 'ETL', category: 'Data' },
  { name: 'Data Analysis', category: 'Data' },
  { name: 'Data Engineering', category: 'Data' },
  { name: 'Machine Learning', category: 'Data Science' },
  { name: 'Deep Learning', category: 'Data Science' },
  { name: 'TensorFlow', category: 'Data Science' },
  { name: 'PyTorch', category: 'Data Science' },
  { name: 'Scikit-learn', category: 'Data Science' },
  { name: 'Pandas', category: 'Data Science' },
  { name: 'NumPy', category: 'Data Science' },
  { name: 'NLP', category: 'Data Science' },
  { name: 'Computer Vision', category: 'Data Science' },
  { name: 'Tableau', category: 'Analytics' },
  { name: 'Power BI', category: 'Analytics' },
  { name: 'Looker', category: 'Analytics' },
  { name: 'Excel', category: 'Analytics' },
  { name: 'AWS', category: 'Cloud & DevOps' },
  { name: 'Azure', category: 'Cloud & DevOps' },
  { name: 'Google Cloud', category: 'Cloud & DevOps' },
  { name: 'Docker', category: 'Cloud & DevOps' },
  { name: 'Kubernetes', category: 'Cloud & DevOps' },
  { name: 'Terraform', category: 'Cloud & DevOps' },
  { name: 'Ansible', category: 'Cloud & DevOps' },
  { name: 'CI/CD', category: 'Cloud & DevOps' },
  { name: 'Jenkins', category: 'Cloud & DevOps' },
  { name: 'GitHub Actions', category: 'Cloud & DevOps' },
  { name: 'GitLab CI', category: 'Cloud & DevOps' },
  { name: 'Linux', category: 'Cloud & DevOps' },
  { name: 'Bash', category: 'Cloud & DevOps' },
  { name: 'Helm', category: 'Cloud & DevOps' },
  { name: 'Prometheus', category: 'Cloud & DevOps' },
  { name: 'Grafana', category: 'Cloud & DevOps' },
  { name: 'System Design', category: 'Architecture' },
  { name: 'Solution Architecture', category: 'Architecture' },
  { name: 'Enterprise Architecture', category: 'Architecture' },
  { name: 'API Design', category: 'Architecture' },
  { name: 'Event-Driven Architecture', category: 'Architecture' },
  { name: 'Git', category: 'Tools' },
  { name: 'Jira', category: 'Tools' },
  { name: 'Confluence', category: 'Tools' },
  { name: 'Figma', category: 'Design' },
  { name: 'Adobe XD', category: 'Design' },
  { name: 'UI Design', category: 'Design' },
  { name: 'UX Design', category: 'Design' },
  { name: 'User Research', category: 'Design' },
  { name: 'Wireframing', category: 'Design' },
  { name: 'Design Systems', category: 'Design' },
  { name: 'Prototyping', category: 'Design' },
  { name: 'Accessibility', category: 'Design' },
  { name: 'Selenium', category: 'QA' },
  { name: 'Cypress', category: 'QA' },
  { name: 'Playwright', category: 'QA' },
  { name: 'Jest', category: 'QA' },
  { name: 'JUnit', category: 'QA' },
  { name: 'API Testing', category: 'QA' },
  { name: 'Postman', category: 'QA' },
  { name: 'Test Automation', category: 'QA' },
  { name: 'Manual Testing', category: 'QA' },
  { name: 'React Native', category: 'Mobile' },
  { name: 'Flutter', category: 'Mobile' },
  { name: 'Android', category: 'Mobile' },
  { name: 'iOS', category: 'Mobile' },
  { name: 'SwiftUI', category: 'Mobile' },
  { name: 'Product Management', category: 'Product' },
  { name: 'Product Strategy', category: 'Product' },
  { name: 'Roadmapping', category: 'Product' },
  { name: 'Agile', category: 'Process' },
  { name: 'Scrum', category: 'Process' },
  { name: 'Kanban', category: 'Process' },
  { name: 'SAFe', category: 'Process' },
  { name: 'Stakeholder Management', category: 'Soft Skills' },
  { name: 'Technical Writing', category: 'Soft Skills' },
  { name: 'Leadership', category: 'Soft Skills' },
  { name: 'Cybersecurity', category: 'Security' },
  { name: 'OAuth', category: 'Security' },
  { name: 'JWT', category: 'Security' },
  { name: 'Penetration Testing', category: 'Security' },
  { name: 'Blockchain', category: 'Emerging' },
  { name: 'IoT', category: 'Emerging' },
  { name: 'SAP', category: 'Enterprise' },
  { name: 'Salesforce', category: 'Enterprise' },
  { name: 'ServiceNow', category: 'Enterprise' },
  { name: 'SharePoint', category: 'Enterprise' },
  { name: 'Power Platform', category: 'Enterprise' },
  { name: 'Prisma', category: 'Tools' },
  { name: 'Supabase', category: 'Tools' },
  { name: 'Firebase', category: 'Tools' },
]
