/** Demo dataset for `npm run db:seed-demo`. All emails use @local.test — safe to delete/re-seed. */

export const DEMO_VENDOR_CODE = 'DEMO-STAFFING'

export const DEMO_RESUME_URLS = [
  'https://www.africau.edu/images/default/sample.pdf',
  'https://pdfobject.com/pdf/sample.pdf',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  'https://www.orimi.com/pdf-test.pdf',
] as const

export const DEMO_PORTAL_USERS = [
  {
    email: 'demo.portal1@local.test',
    name: 'Aisha Mehta',
    password: 'DevTest123!',
    applyToJobCode: 'DEMO-SWE-01',
  },
  {
    email: 'demo.portal2@local.test',
    name: 'Rohan Kapoor',
    password: 'DevTest123!',
    applyToJobCode: 'DEMO-PM-01',
  },
  {
    email: 'demo.portal3@local.test',
    name: 'Neha Iyer',
    password: 'DevTest123!',
    applyToJobCode: 'DEMO-DEVOPS-01',
  },
  {
    email: 'demo.portal4@local.test',
    name: 'Vikram Desai',
    password: 'DevTest123!',
    applyToJobCode: 'DEMO-UX-01',
  },
  {
    email: 'demo.portal5@local.test',
    name: 'Priya Nair',
    password: 'DevTest123!',
    applyToJobCode: 'DEMO-DATA-01',
  },
  /** Logged-in candidate account with no application yet (portal shows “apply to get started”). */
  {
    email: 'demo.portal-browse@local.test',
    name: 'Karan Joshi',
    password: 'DevTest123!',
    applyToJobCode: null,
  },
  {
    email: 'demo.portal-browse2@local.test',
    name: 'Meera Shah',
    password: 'DevTest123!',
    applyToJobCode: null,
  },
] as const

export const DEMO_REQUIREMENTS = [
  {
    jobCode: 'DEMO-SWE-01',
    title: 'Senior Software Engineer',
    department: 'Engineering',
    hiringManager: 'Dev Hiring Manager',
    client: 'Acme Corp',
    location: 'Bangalore (Hybrid)',
    priority: 'HIGH',
    openings: 3,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: true,
    primarySkills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'REST APIs'],
    secondarySkills: ['AWS', 'Docker', 'CI/CD', 'System Design'],
    description: 'Build and scale our hiring platform frontend and API.',
    jobDescription:
      'We need a senior engineer with strong TypeScript, React, and Node.js experience. PostgreSQL and REST API design required. AWS and Docker are nice to have.',
  },
  {
    jobCode: 'DEMO-PM-01',
    title: 'Product Manager',
    department: 'Product',
    hiringManager: 'Dev HR Head',
    client: 'Acme Corp',
    location: 'Mumbai (Remote)',
    priority: 'MEDIUM',
    openings: 1,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: false,
    primarySkills: ['Product Strategy', 'Roadmapping', 'Stakeholder Management', 'Agile'],
    secondarySkills: ['SQL', 'Analytics', 'B2B SaaS'],
    description: 'Own the ATS product roadmap and delivery.',
    jobDescription:
      'Product manager with B2B SaaS background, agile delivery, and strong stakeholder communication.',
  },
  {
    jobCode: 'DEMO-DEVOPS-01',
    title: 'DevOps Engineer',
    department: 'Platform',
    hiringManager: 'Dev Team Lead',
    client: 'Internal',
    location: 'Hyderabad',
    priority: 'HIGH',
    openings: 2,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: true,
    primarySkills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD', 'Linux'],
    secondarySkills: ['Prometheus', 'Grafana', 'Helm'],
    description: 'Run production infrastructure for the ATS stack.',
    jobDescription:
      'DevOps engineer skilled in Kubernetes, Terraform, AWS, and CI/CD pipelines on Linux.',
  },
  {
    jobCode: 'DEMO-UX-01',
    title: 'UX Designer',
    department: 'Design',
    hiringManager: 'Dev Hiring Manager',
    client: 'Acme Corp',
    location: 'Remote',
    priority: 'LOW',
    openings: 1,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: false,
    primarySkills: ['Figma', 'User Research', 'Wireframing', 'Design Systems'],
    secondarySkills: ['HTML', 'CSS', 'Accessibility'],
    description: 'Design recruiter and candidate experiences.',
    jobDescription:
      'UX designer with Figma, user research, wireframing, and design system experience.',
  },
  {
    jobCode: 'DEMO-DATA-01',
    title: 'Data Analyst',
    department: 'Analytics',
    hiringManager: 'Dev HR Manager',
    client: 'Internal',
    location: 'Chennai',
    priority: 'MEDIUM',
    openings: 2,
    filled: 0,
    status: 'LIVE' as const,
    visibleToCandidates: true,
    visibleToVendors: true,
    primarySkills: ['SQL', 'Python', 'Tableau', 'Excel'],
    secondarySkills: ['dbt', 'Snowflake', 'Statistics'],
    description: 'Hiring funnel analytics and reporting.',
    jobDescription:
      'Data analyst with SQL, Python, Tableau, and strong Excel skills for recruiting metrics.',
  },
  {
    jobCode: 'DEMO-HR-01',
    title: 'HR Coordinator',
    department: 'HR',
    hiringManager: 'Dev HR Head',
    client: 'Internal',
    location: 'Delhi NCR',
    priority: 'LOW',
    openings: 1,
    filled: 0,
    status: 'PENDING_APPROVAL' as const,
    visibleToCandidates: false,
    visibleToVendors: false,
    primarySkills: ['Onboarding', 'HR Operations', 'Communication'],
    secondarySkills: ['ATS', 'Compliance'],
    description: 'Coordinate interviews and offers.',
    jobDescription: 'HR coordinator for interview scheduling and offer coordination.',
  },
] as const

export type DemoCandidateSeed = {
  email: string
  name: string
  role: string
  status: string
  source: string
  jobCode?: string | null
  phone?: string
  location?: string
  totalExperience?: string
  currentCompany?: string
  primarySkills?: string[]
  secondarySkills?: string[]
  resumeSnippet: string
  vendorSubmitted?: boolean
}

export const DEMO_CANDIDATES: DemoCandidateSeed[] = [
  {
    email: 'demo.cand01@local.test',
    name: 'Arjun Pillai',
    role: 'Full Stack Developer',
    status: 'SCREENING',
    source: 'LinkedIn',
    jobCode: 'DEMO-SWE-01',
    location: 'Bangalore',
    totalExperience: '6 Years',
    currentCompany: 'TechNova',
    primarySkills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL'],
    secondarySkills: ['AWS', 'Docker'],
    resumeSnippet:
      'Arjun Pillai — Full Stack Developer with 6 years experience. Skills: TypeScript, React, Node.js, PostgreSQL, REST APIs, AWS, Docker.',
  },
  {
    email: 'demo.cand02@local.test',
    name: 'Sneha Reddy',
    role: 'Backend Engineer',
    status: 'SHORTLISTED',
    source: 'Referral',
    jobCode: 'DEMO-SWE-01',
    location: 'Hyderabad',
    totalExperience: '8 Years',
    currentCompany: 'CloudBase',
    primarySkills: ['Node.js', 'TypeScript', 'PostgreSQL', 'System Design'],
    secondarySkills: ['Kubernetes', 'Redis'],
    resumeSnippet:
      'Sneha Reddy — Backend engineer, 8 years. Node.js, TypeScript, PostgreSQL, REST APIs, system design, Kubernetes.',
  },
  {
    email: 'demo.cand03@local.test',
    name: 'Michael Chen',
    role: 'Software Engineer',
    status: 'INTERVIEW',
    source: 'Recruiter Added',
    jobCode: 'DEMO-SWE-01',
    location: 'Remote',
    totalExperience: '5 Years',
    currentCompany: 'StartupHub',
    primarySkills: ['React', 'TypeScript', 'Node.js'],
    secondarySkills: ['GraphQL', 'Jest'],
    resumeSnippet:
      'Michael Chen — Software engineer, React, TypeScript, Node.js, PostgreSQL, CI/CD experience.',
  },
  {
    email: 'demo.cand04@local.test',
    name: 'Fatima Hassan',
    role: 'Product Manager',
    status: 'OFFER',
    source: 'LinkedIn',
    jobCode: 'DEMO-PM-01',
    location: 'Mumbai',
    totalExperience: '7 Years',
    currentCompany: 'SaaSify',
    primarySkills: ['Product Strategy', 'Roadmapping', 'Agile', 'B2B SaaS'],
    secondarySkills: ['SQL', 'Analytics'],
    resumeSnippet:
      'Fatima Hassan — Product Manager, 7 years B2B SaaS, agile, roadmapping, stakeholder management, SQL analytics.',
  },
  {
    email: 'demo.cand05@local.test',
    name: 'David Okonkwo',
    role: 'Platform Engineer',
    status: 'SOURCED',
    source: 'Vendor: Demo Staffing Co',
    jobCode: 'DEMO-DEVOPS-01',
    location: 'Pune',
    totalExperience: '4 Years',
    currentCompany: 'InfraWorks',
    primarySkills: ['AWS', 'Terraform', 'Linux', 'CI/CD'],
    secondarySkills: ['Kubernetes', 'Helm'],
    resumeSnippet:
      'David Okonkwo — Platform engineer, AWS, Terraform, Kubernetes, CI/CD, Linux administration.',
    vendorSubmitted: true,
  },
  {
    email: 'demo.cand06@local.test',
    name: 'Lisa Wong',
    role: 'SRE',
    status: 'SCREENING',
    source: 'Vendor: Demo Staffing Co',
    jobCode: 'DEMO-DEVOPS-01',
    location: 'Singapore',
    totalExperience: '9 Years',
    currentCompany: 'GlobalOps',
    primarySkills: ['Kubernetes', 'AWS', 'Prometheus', 'Grafana'],
    secondarySkills: ['Terraform', 'Python'],
    resumeSnippet:
      'Lisa Wong — SRE with Kubernetes, AWS, Prometheus, Grafana, Terraform, CI/CD pipelines.',
    vendorSubmitted: true,
  },
  {
    email: 'demo.cand07@local.test',
    name: 'James Miller',
    role: 'DevOps Consultant',
    status: 'APPLIED',
    source: 'Vendor: Demo Staffing Co',
    jobCode: 'DEMO-DEVOPS-01',
    location: 'Chennai',
    totalExperience: '3 Years',
    currentCompany: 'ConsultCo',
    primarySkills: ['Docker', 'AWS', 'Linux'],
    secondarySkills: ['Jenkins', 'Bash'],
    resumeSnippet:
      'James Miller — DevOps consultant, Docker, AWS, Linux, Jenkins, CI/CD.',
    vendorSubmitted: true,
  },
  {
    email: 'demo.cand08@local.test',
    name: 'Elena Petrova',
    role: 'UX Designer',
    status: 'INTERVIEW',
    source: 'Referral',
    jobCode: 'DEMO-UX-01',
    location: 'Berlin (Remote)',
    totalExperience: '5 Years',
    currentCompany: 'DesignLab',
    primarySkills: ['Figma', 'User Research', 'Wireframing'],
    secondarySkills: ['Accessibility', 'HTML', 'CSS'],
    resumeSnippet:
      'Elena Petrova — UX designer, Figma, user research, wireframing, design systems, accessibility.',
  },
  {
    email: 'demo.cand09@local.test',
    name: 'Tom Bradley',
    role: 'Product Designer',
    status: 'HIRED',
    source: 'Recruiter Added',
    jobCode: 'DEMO-UX-01',
    location: 'London',
    totalExperience: '10 Years',
    currentCompany: 'CreativeMinds',
    primarySkills: ['Figma', 'Design Systems', 'Prototyping'],
    secondarySkills: ['Framer', 'CSS'],
    resumeSnippet:
      'Tom Bradley — Product designer, Figma, design systems, prototyping, HTML CSS.',
  },
  {
    email: 'demo.cand10@local.test',
    name: 'Anita Krishnan',
    role: 'Data Analyst',
    status: 'SHORTLISTED',
    source: 'LinkedIn',
    jobCode: 'DEMO-DATA-01',
    location: 'Chennai',
    totalExperience: '4 Years',
    currentCompany: 'DataFirst',
    primarySkills: ['SQL', 'Python', 'Tableau', 'Excel'],
    secondarySkills: ['Statistics', 'Power BI'],
    resumeSnippet:
      'Anita Krishnan — Data analyst, SQL, Python, Tableau, Excel, hiring analytics and reporting.',
  },
  {
    email: 'demo.cand11@local.test',
    name: 'Carlos Mendez',
    role: 'Analytics Engineer',
    status: 'SCREENING',
    source: 'Vendor: Demo Staffing Co',
    jobCode: 'DEMO-DATA-01',
    location: 'Mexico City (Remote)',
    totalExperience: '6 Years',
    currentCompany: 'MetricsCo',
    primarySkills: ['SQL', 'Python', 'dbt'],
    secondarySkills: ['Snowflake', 'Tableau'],
    resumeSnippet:
      'Carlos Mendez — Analytics engineer, SQL, Python, dbt, Snowflake, Tableau, statistics.',
    vendorSubmitted: true,
  },
  {
    email: 'demo.cand12@local.test',
    name: 'Yuki Tanaka',
    role: 'BI Analyst',
    status: 'REJECTED',
    source: 'Recruiter Added',
    jobCode: 'DEMO-DATA-01',
    location: 'Tokyo',
    totalExperience: '2 Years',
    currentCompany: 'RetailBI',
    primarySkills: ['Excel', 'SQL'],
    secondarySkills: ['R'],
    resumeSnippet:
      'Yuki Tanaka — BI analyst, Excel, SQL, basic reporting.',
  },
  {
    email: 'demo.cand13@local.test',
    name: 'Olivia Grant',
    role: 'Frontend Developer',
    status: 'SOURCED',
    source: 'LinkedIn',
    jobCode: null,
    location: 'Austin',
    totalExperience: '3 Years',
    currentCompany: 'WebCraft',
    primarySkills: ['React', 'TypeScript', 'CSS'],
    secondarySkills: ['Next.js'],
    resumeSnippet:
      'Olivia Grant — Frontend developer, React, TypeScript, CSS, Next.js, REST APIs.',
  },
  {
    email: 'demo.cand14@local.test',
    name: 'Raj Malhotra',
    role: 'Engineering Manager',
    status: 'SOURCED',
    source: 'Referral',
    jobCode: null,
    location: 'Gurgaon',
    totalExperience: '12 Years',
    currentCompany: 'BigTech India',
    primarySkills: ['Leadership', 'System Design', 'TypeScript'],
    secondarySkills: ['Hiring', 'Agile'],
    resumeSnippet:
      'Raj Malhotra — Engineering manager, system design, TypeScript, team leadership, agile.',
  },
  {
    email: 'demo.cand15@local.test',
    name: 'Sophie Laurent',
    role: 'QA Engineer',
    status: 'SOURCED',
    source: 'Recruiter Added',
    jobCode: null,
    location: 'Paris',
    totalExperience: '5 Years',
    currentCompany: 'QualityFirst',
    primarySkills: ['Selenium', 'Jest', 'API Testing'],
    secondarySkills: ['Cypress', 'Postman'],
    resumeSnippet:
      'Sophie Laurent — QA engineer, Selenium, Jest, API testing, Cypress, Postman.',
  },
  {
    email: 'demo.cand16@local.test',
    name: 'Ben Carter',
    role: 'Mobile Developer',
    status: 'APPLIED',
    source: 'Direct',
    jobCode: 'DEMO-SWE-01',
    location: 'Toronto',
    totalExperience: '4 Years',
    currentCompany: 'AppWorks',
    primarySkills: ['React Native', 'TypeScript'],
    secondarySkills: ['Firebase'],
    resumeSnippet:
      'Ben Carter — Mobile developer, React Native, TypeScript, Node.js, REST APIs.',
  },
  {
    email: 'demo.cand17@local.test',
    name: 'Grace Kim',
    role: 'Technical Writer',
    status: 'SCREENING',
    source: 'Direct',
    jobCode: null,
    location: 'Seoul',
    totalExperience: '6 Years',
    currentCompany: 'DocuTech',
    primarySkills: ['Documentation', 'API Docs', 'Markdown'],
    secondarySkills: ['Confluence', 'Git'],
    resumeSnippet:
      'Grace Kim — Technical writer, API documentation, Markdown, Confluence, Git.',
  },
]
